"""Sole owner of the project's variable start-location scheme (image + PCM).

Wire format v1: fixed bootstrap [magic, nonce, length, header HMAC], then
payload + payload HMAC in a keyed circular region excluding the bootstrap.
Use a random shared secret (at least 32 random bytes), not a human password.
This authenticates embedded data; it neither encrypts it nor authenticates all
unused carrier samples. See start_location_notes.md for the security boundary.
"""

from dataclasses import dataclass
import hmac
import json
import secrets
import struct
from typing import Sequence

MAGIC = b"SL01"
_PREFIX = struct.Struct(">4s16sQ")
TAG_BYTES = 32
HEADER_BYTES = _PREFIX.size + TAG_BYTES


class WrongStartLocationError(ValueError):
    """Wrong location/key/settings, missing frame, or modified embedded data.

    These causes cannot be reliably distinguished from authentication failure.
    """


@dataclass(frozen=True)
class CarrierSpec:
    media: str
    total_units: int
    bits_per_unit: int
    unit_width: int
    dimensions: tuple[int, ...]

    def __post_init__(self):
        if self.media not in ("image", "audio"):
            raise ValueError("media must be image or audio")
        if self.unit_width not in (8, 16, 24, 32):
            raise ValueError("unsupported channel/sample width")
        if not 1 <= self.bits_per_unit <= min(8, self.unit_width):
            raise ValueError("LSB count must be between 1 and 8")
        if self.total_units <= 0 or not self.dimensions or any(d <= 0 for d in self.dimensions):
            raise ValueError("carrier dimensions must be positive")

    @classmethod
    def image(cls, width, height, channels=3, bits=1):
        return cls("image", width * height * channels, bits, 8, (width, height, channels))

    @classmethod
    def audio(cls, frames, channels, sample_rate, sample_width=16, bits=1):
        """One unit is one PCM sample; multichannel samples are interleaved."""
        return cls("audio", frames * channels, bits, sample_width,
                   (frames, channels, sample_rate))

    @property
    def header_units(self):
        return _units(HEADER_BYTES, self.bits_per_unit)

    def context(self):
        return json.dumps(["start-location-v1", self.media, self.total_units,
                           self.bits_per_unit, self.unit_width, self.dimensions],
                          separators=(",", ":")).encode("ascii")


def _units(byte_count, bits):
    return (byte_count * 8 + bits - 1) // bits


def required_units(payload_size: int, spec: CarrierSpec) -> int:
    if payload_size < 0:
        raise ValueError("payload size cannot be negative")
    return spec.header_units + _units(payload_size + TAG_BYTES, spec.bits_per_unit)


def _mac(key, label, spec, data):
    if isinstance(key, str):
        key = key.encode("utf-8")
    if not isinstance(key, bytes) or not key:
        raise ValueError("a nonempty shared secret is required")
    subkey = hmac.digest(key, b"start-location-v1/" + label, "sha256")
    return hmac.digest(subkey, spec.context() + b"\x00" + data, "sha256")


def derive_start_location(key, spec: CarrierSpec, nonce: bytes) -> int:
    """Return absolute channel/sample index; encoder and decoder use this API.

    Rejection sampling avoids modulo bias. The nonce is public and must be
    freshly generated by the encoder. Start values can collide in small covers.
    """
    if len(nonce) != 16:
        raise ValueError("nonce must contain 16 bytes")
    slots = spec.total_units - spec.header_units
    if slots <= 0 or slots >= 2**256:
        raise ValueError("carrier has no usable start-location region")
    limit = 2**256 - (2**256 % slots)
    counter = 0
    while True:
        value = int.from_bytes(_mac(key, b"location", spec,
                                   nonce + counter.to_bytes(8, "big")), "big")
        if value < limit:
            return spec.header_units + value % slots
        counter += 1


def select_start_location(key, spec: CarrierSpec, payload_size: int):
    """Encoder: return (start index, authenticated bootstrap header)."""
    if required_units(payload_size, spec) > spec.total_units:
        raise ValueError("Payload and authenticated framing exceed carrier capacity")
    nonce = secrets.token_bytes(16)
    prefix = _PREFIX.pack(MAGIC, nonce, payload_size)
    header = prefix + _mac(key, b"header", spec, prefix)
    return derive_start_location(key, spec, nonce), header


def recover_start_location(key, spec: CarrierSpec, header: bytes):
    """Decoder: authenticate before trusting length; return (index, length)."""
    if len(header) != HEADER_BYTES:
        raise WrongStartLocationError("Wrong Start Location: invalid bootstrap size")
    prefix, tag = header[:-TAG_BYTES], header[-TAG_BYTES:]
    if not hmac.compare_digest(tag, _mac(key, b"header", spec, prefix)):
        raise WrongStartLocationError("Wrong Start Location: bootstrap authentication failed")
    magic, nonce, length = _PREFIX.unpack(prefix)
    if magic != MAGIC or required_units(length, spec) > spec.total_units:
        raise WrongStartLocationError("Wrong Start Location: invalid frame or capacity")
    return derive_start_location(key, spec, nonce), length


def _indices(spec, start, count, bootstrap=False):
    base = 0 if bootstrap else spec.header_units
    size = spec.header_units if bootstrap else spec.total_units - base
    for offset in range(count):
        yield base + (start - base + offset) % size


def _write(units, data, spec, start, bootstrap=False):
    bits = spec.bits_per_unit
    mask = (1 << bits) - 1
    accumulator = available = 0
    indices = iter(_indices(spec, start, _units(len(data), bits), bootstrap))
    for byte in data:
        accumulator = (accumulator << 8) | byte
        available += 8
        while available >= bits:
            available -= bits
            index = next(indices)
            units[index] = (units[index] & ~mask) | ((accumulator >> available) & mask)
        accumulator &= (1 << available) - 1
    if available:
        index = next(indices)
        units[index] = (units[index] & ~mask) | (accumulator << (bits - available))


def _read(units, byte_count, spec, start, bootstrap=False):
    result = bytearray()
    accumulator = available = 0
    mask = (1 << spec.bits_per_unit) - 1
    for index in _indices(spec, start, _units(byte_count, spec.bits_per_unit), bootstrap):
        accumulator = (accumulator << spec.bits_per_unit) | (units[index] & mask)
        available += spec.bits_per_unit
        while available >= 8 and len(result) < byte_count:
            available -= 8
            result.append((accumulator >> available) & 255)
        accumulator &= (1 << available) - 1
    return bytes(result)


def embed_units(units: Sequence[int], payload: bytes, key, spec: CarrierSpec, *, demo_log=None) -> list[int]:
    """Return a modified copy of RGB channels or signed/unsigned PCM samples."""
    if len(units) != spec.total_units:
        raise ValueError("carrier length does not match specification")
    start, header = select_start_location(key, spec, len(payload))
    tag = _mac(key, b"payload", spec, header + start.to_bytes(32, "big") + payload)
    output = list(units)
    _write(output, header, spec, 0, bootstrap=True)
    _write(output, payload + tag, spec, start)
    if demo_log:
        demo_log(f"ENCODER | nonce={header[4:20].hex()} | media={spec.media} | "
                 f"LSBs={spec.bits_per_unit} | derived start index={start} (zero-based)")
    return output


def extract_units(units: Sequence[int], key, spec: CarrierSpec, *, start_index=None, demo_log=None) -> bytes:
    """Recover and authenticate data. Optional explicit index detects wrong starts."""
    if len(units) != spec.total_units or required_units(0, spec) > spec.total_units:
        raise WrongStartLocationError("Wrong Start Location: carrier missing or too small")
    header = _read(units, HEADER_BYTES, spec, 0, bootstrap=True)
    start, length = recover_start_location(key, spec, header)
    if demo_log:
        demo_log(f"DECODER | nonce={header[4:20].hex()} | media={spec.media} | "
                 f"LSBs={spec.bits_per_unit} | recovered start index={start} (zero-based)")
    if start_index is not None and start_index != start:
        raise WrongStartLocationError("Wrong Start Location: supplied index differs from derived index")
    frame = _read(units, length + TAG_BYTES, spec, start)
    payload, tag = frame[:-TAG_BYTES], frame[-TAG_BYTES:]
    expected = _mac(key, b"payload", spec, header + start.to_bytes(32, "big") + payload)
    if not hmac.compare_digest(tag, expected):
        raise WrongStartLocationError("Wrong Start Location: payload authentication failed (or tampered data)")
    if demo_log:
        demo_log("RECOVERY | PASS: payload authentication succeeded at recovered index")
        # Demonstration only: read a neighbouring index, leaving the real
        # extraction result and carrier unchanged. Do not bypass normal checks.
        wrong = spec.header_units + (start - spec.header_units + 1) % (
            spec.total_units - spec.header_units)
        wrong_frame = _read(units, length + TAG_BYTES, spec, wrong)
        wrong_expected = _mac(key, b"payload", spec,
                              header + wrong.to_bytes(32, "big") + wrong_frame[:-TAG_BYTES])
        valid = hmac.compare_digest(wrong_frame[-TAG_BYTES:], wrong_expected)
        result = "UNEXPECTED authentication success" if valid else "Wrong Start Location: HMAC rejected"
        demo_log(f"WRONG-INDEX EXPERIMENT | attempted index={wrong} | {result} | "
                 "demo experiment only; actual upload recovery succeeded")
    return payload
